### ISSUE TITLE
How to get HTML file to run wasm as well?

### ISSUE THREAD

**Issue by Nerdyvedi** [s0l0ist/bazel-emscripten#1]
Hi, I don't have a lot of experience with bazel and emscripten.

Want to generate the html using emscripten for testing embedded Javascript.

For example, In Emscripten docs ,it is generated as follows
`./emcc tests/hello_world.c -o hello.html`

Thank you

**Comment by s0l0ist** [comment]
This project uses Bazel to build a WASM binary from a C++ library. This avoids having to write your own `./emcc ..` build commands.

Unfortunately, the configuration in this repo does not generate any HTML; however, there is a [folder](https://github.com/s0l0ist/bazel-emscripten/tree/master/hello-world/javascript/html) containing two HTML files that reference the bundled output from `rollup`.
