### ISSUE TITLE
How can I add a new class and function to the two that you have added?

### ISSUE THREAD

**Issue by constantvariable1** [s0l0ist/bazel-emscripten#4]
So far I have made a new cpp file and hcc file just like you have in the cpp folder. included them in the hello-world.cpp file which has the emscripten binding. I have added it to the bazel build file and it builds successfully also.

ERROR: /Users/user1/MyDocuments/work/new/bazel-emscripten/hello-world/javascript/BUILD:27:10: Compiling hello-world/javascript/bindings/hello-world.cpp failed: (Exit 1): emcc.sh failed: error executing command hello-world/javascript/toolchain/emcc.sh -MD -MF bazel-out/wasm-opt/bin/hello-world/javascript/_objs/hello-world-wasm.js/hello-world.d ... (remaining 22 argument(s) skipped)
hello-world/javascript/bindings/hello-world.cpp:20:24: error: use of undeclared identifier 'MyHello'
    emscripten::class_<MyHello>("MyHello")
                       ^
hello-world/javascript/bindings/hello-world.cpp:22:34: error: use of undeclared identifier 'MyHello'
        .class_function("Heya", &MyHello::Heya); 
                                 ^
2 errors generated.

this happens. could you please help.

**Comment by s0l0ist** [comment]
If you're creating new files, you need to update the bezel dependencies:
- in [cpp/BUILD ](https://github.com/s0l0ist/bazel-emscripten/blob/master/hello-world/cpp/BUILD)
- in [javascript/BUILD](https://github.com/s0l0ist/bazel-emscripten/blob/master/hello-world/javascript/BUILD)

Then you should be able to compile successfully.
