### ISSUE TITLE
npm run demo:wasm fails

### ISSUE THREAD

**Issue by ouceduxzk** [s0l0ist/bazel-emscripten#6]
Thanks for the nice work, I have a problem with "npm run demo:wasm" after build , the error on my ubuntu18 is 

`
> bazel-emscripten@1.0.0 demo:wasm /home/zaikun/technology/bazel-emscripten
> RUN_DEMO=wasm node ./hello-world/javascript/examples/demo.js

module.js:549
    throw err;
    ^

Error: Cannot find module '../dist/wasm/umd'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)

here is the log 
16 error owner ls Couldn't get owner data bazel-emscripten
17 verbose stack Error: Not found : bazel-emscripten
17 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:252:14)
17 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
17 verbose stack     at emitTwo (events.js:126:13)
17 verbose stack     at Request.emit (events.js:214:7)
17 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
17 verbose stack     at emitOne (events.js:121:20)
17 verbose stack     at Request.emit (events.js:211:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
18 verbose statusCode 404
19 verbose pkgid bazel-emscripten
20 verbose cwd /home/zaikun/technology/bazel-emscripten
21 error Linux 5.4.0-86-generic
22 error argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "bazel-emscripten"
23 error node v8.10.0
24 error npm  v3.5.2
25 error code E404
26 error 404 Not found : bazel-emscripten
27 error 404
28 error 404 'bazel-emscripten' is not in the npm registry.
29 error 404 You should bug the author to publish it (or use the name yourself!)
30 error 404 Note that you can also install from a
31 error 404 tarball, folder, http url, or git url.
32 verbose exit [ 1, true ]
                                  
`

Seems the owner issue ?

**Comment by s0l0ist** [comment]
did you run `npm i` then `npm run rollup`?
